# fly.toml app configuration file for ScreenMerch Frontend

app = "copy5-frontend"
primary_region = "sjc"

[build]
  dockerfile = "frontend_Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  SUPABASE_URL = "https://sojxbydpcdcdzfdtbypd.supabase.co"
  # Note: Sensitive keys should be set via fly secrets, not in fly.toml
