/**
 * Visual themes for homepage reserve slots (20 creator storefronts).
 * Intro video is a separate first card → 21 tiles = 7 rows × 3 columns.
 */
export const RESERVE_SLOT_THEMES = [
  {
    spot: 1,
    theme: 'film',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    icon: '🎬',
    tagline: 'Your story on screen',
    pattern: 'filmstrip',
  },
  {
    spot: 2,
    theme: 'creator',
    gradient: 'linear-gradient(145deg, #667eea 0%, #764ba2 100%)',
    icon: '✨',
    tagline: 'Build your brand',
    pattern: 'sparkle',
  },
  {
    spot: 3,
    theme: 'merch',
    gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    icon: '👕',
    tagline: 'Turn frames into merch',
    pattern: 'dots',
  },
  {
    spot: 4,
    theme: 'money',
    gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    icon: '💰',
    tagline: 'Monetize your moments',
    pattern: 'coins',
  },
  {
    spot: 5,
    theme: 'camera',
    gradient: 'linear-gradient(160deg, #2c3e50 0%, #4ca1af 100%)',
    icon: '📸',
    tagline: 'Capture & sell',
    pattern: 'lens',
  },
  {
    spot: 6,
    theme: 'popcorn',
    gradient: 'linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)',
    icon: '🍿',
    tagline: 'Cinema vibes',
    pattern: 'warm',
  },
  {
    spot: 7,
    theme: 'director',
    gradient: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
    icon: '🎥',
    tagline: "Director's cut",
    pattern: 'clapper',
  },
  {
    spot: 8,
    theme: 'palette',
    gradient: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    icon: '🎨',
    tagline: 'Design your storefront',
    pattern: 'brush',
  },
  {
    spot: 9,
    theme: 'star',
    gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    icon: '⭐',
    tagline: 'Rise as a creator',
    pattern: 'stars',
  },
  {
    spot: 10,
    theme: 'cart',
    gradient: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    icon: '🛒',
    tagline: 'Fans shop your clips',
    pattern: 'soft',
  },
  {
    spot: 11,
    theme: 'reel',
    gradient: 'linear-gradient(135deg, #5f2c82 0%, #49a09d 100%)',
    icon: '🎞️',
    tagline: 'Clip. List. Earn.',
    pattern: 'reel',
  },
  {
    spot: 12,
    theme: 'fire',
    gradient: 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)',
    icon: '🔥',
    tagline: 'Hot takes, hot sales',
    pattern: 'flame',
  },
  {
    spot: 13,
    theme: 'crown',
    gradient: 'linear-gradient(135deg, #c79081 0%, #dfa579 100%)',
    icon: '👑',
    tagline: 'Own your channel',
    pattern: 'gold',
  },
  {
    spot: 14,
    theme: 'rocket',
    gradient: 'linear-gradient(135deg, #360033 0%, #0b8793 100%)',
    icon: '🚀',
    tagline: 'Launch your shop',
    pattern: 'space',
  },
  {
    spot: 15,
    theme: 'gift',
    gradient: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%)',
    icon: '🎁',
    tagline: 'Gifts fans will love',
    pattern: 'ribbon',
  },
  {
    spot: 16,
    theme: 'ticket',
    gradient: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)',
    icon: '🎟️',
    tagline: 'Limited storefronts',
    pattern: 'ticket',
  },
  {
    spot: 17,
    theme: 'diamond',
    gradient: 'linear-gradient(135deg, #834d9b 0%, #d04ed6 100%)',
    icon: '💎',
    tagline: 'Premium placement',
    pattern: 'gem',
  },
  {
    spot: 18,
    theme: 'wave',
    gradient: 'linear-gradient(135deg, #2e3192 0%, #1bffff 100%)',
    icon: '🌊',
    tagline: 'Ride the wave',
    pattern: 'wave',
  },
  {
    spot: 19,
    theme: 'spotlight',
    gradient: 'linear-gradient(135deg, #232526 0%, #414345 100%)',
    icon: '💡',
    tagline: 'Step into the light',
    pattern: 'spotlight',
  },
  {
    spot: 20,
    theme: 'stage',
    gradient: 'linear-gradient(135deg, #141E30 0%, #243B55 100%)',
    icon: '🏆',
    tagline: 'Claim your stage',
    pattern: 'stars',
  },
];

/** Soft-launch creator capacity (matches numbered reserve cards). */
export const TOTAL_CREATOR_SPOTS = 20;
export const INTRO_POSITION = 0;
